#!/usr/bin/env python3
"""Put an account back from a dump, when somebody decides to.

The hole this closes is the one the backup opens: a dump that has never been
restored is a hope, not a copy. tool/account/backup_accounts.py writes the
account to a file every night, and docs/account-backup.md writes out the
statements that turn one of those files back into rows - as a recipe, run into
temporary copies of the tables inside transactions that were rolled back, and
never once against the tables themselves. This is that recipe as a program, so
that the day it is needed is not the day it is first tried.

What it does, in order. It reads a dump and checks it (the reader is
backup_accounts' own, so a file this cannot read is a file the backup cannot
read either). It resolves the account the rows belong to, because user_id is a
foreign key to auth.users and a restore cannot invent a collector. It reads what
the tables hold for that account now and says exactly what restoring would
change: how many rows would be inserted, how many replaced, how many removed,
and how many are already identical. Then, unless it was told --apply, it runs
the whole restore inside a transaction that is rolled back, and checks afterwards
that the tables hold what they held.

What it refuses. To run at all without a database URL. To write anything without
being told whose rows: --user for one collector, --every-account for the case
this exists for - the project is gone and every account is coming back. To
restore rows for an email that is not in auth.users. To touch a table the dump
does not hold (a version-1 dump has no deck_cards in it, and restoring one would
give every collector their decks back with none of their cards in them, so the
plan says so in that many words).

What it is not. It is not a merge. A restore replaces the account's rows with the
rows in the file: anything the collector added after that file was taken is not
in it and will be removed by the delete that precedes the insert. That is what a
restore is for, and it is the wrong tool for one bad delete this morning - the
app's own sync settles that case on updated_at, and its tombstones are in the
dump for exactly that reason.

Usage, from the repository root or from /home/zixen/arcanum:

    set -a; . /home/zixen/arcanum/supabase.env; set +a
    python3 tool/account/restore_accounts.py --user someone@example.com
    python3 tool/account/restore_accounts.py --from account-2026-09-21T071019Z.json.gz --user someone@example.com --apply
    python3 tool/account/restore_accounts.py --every-account --apply

Exit status is 0 unless the dump could not be read, the account could not be
found, or a statement failed.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

# backup_accounts is this file's other half: the reader, the format, the
# connection rules and the dump directory are all its, and a second copy of any
# of them is a second thing to keep in step. The two directories are searched the
# way it searches them - the repository layout first, the flat deployment of the
# host second - so this runs from a checkout and from /home/zixen/arcanum alike.
HERE = os.path.dirname(os.path.abspath(__file__))
for _candidate in (os.path.dirname(HERE), HERE):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)
import backup_accounts as backup  # noqa: E402

# The columns that identify a row inside its table, which is all this file needs
# to talk about one row of a dump. collection_entries and decks carry a key of
# their own; a deck's lines are named by which deck, which printing and which
# board, because a line has no id and is not meant to.
KEYS = {
    "collection_entries": ("id",),
    "decks": ("id",),
    "deck_cards": ("user_id", "deck_sync_id", "card_id", "board"),
}

# The tables whose key is generated by the database. decks.id is
# "generated always as identity", so an insert that carries the dumped ids has to
# say overriding system value - which is the clause the recipe in
# docs/account-backup.md needed, and the reason it was worth writing down.
GENERATED_KEYS = ("decks",)

# How many rows go into one insert. A whole account in a single statement would
# work and would be one enormous thing to hand psql; the transaction is what
# makes the batches one write, so the size is only about the statement.
BATCH = 250

USER_COLUMN = "user_id"


def table_columns_of(header, table):
    """The columns one dump says a table has, in the order it wrote them."""
    return list(header["columns"][table])


def key_of(table, row):
    """The tuple that names one row of a dump inside its table."""
    parts = []
    for column in KEYS.get(table, ()):
        value = row.get(column)
        parts.append("" if value is None else str(value))
    return tuple(parts)


def user_id_of(db_url, email, timeout=backup.TIMEOUT):
    """The account behind an email address, or None.

    auth.users is where the identities live and the account tables point at it, so
    a restore for an address that is not there has nowhere to put its rows. The
    users themselves are the one part of this system no dump holds: an account
    has to exist before its collection can come back.
    """
    rows = backup.psql_lines(
        db_url,
        "select id::text from auth.users where lower(email) = lower("
        + backup.sql_text(email) + ") limit 1;",
        timeout)
    for line in rows:
        if line.strip():
            return line.strip()
    return None


def live_rows(db_url, table, columns, user_ids, timeout=backup.TIMEOUT):
    """What the table holds for those accounts now, rendered as the dump is.

    Text, in the dump's own shape, so the two readings compare equal: every value
    is cast the way backup_accounts casts it, because numeric and timestamptz have
    no exact JSON form and a comparison of parsed floats is a comparison of
    something else.
    """
    if not user_ids:
        return []
    pairs = ", ".join(backup.sql_text(column) + ", " + backup.quote_ident(column)
                      + "::text" for column in columns)
    array = "array[" + ", ".join(backup.sql_text(u) for u in sorted(user_ids)) + "]::uuid[]"
    sql = ("select json_build_object(" + pairs + ")::text"
           + "  from public." + backup.quote_ident(table)
           + " where " + backup.quote_ident(USER_COLUMN) + " = any (" + array + ")"
           + " order by 1;")
    rows = backup.psql_lines(db_url, sql, timeout)
    return [json.loads(line) for line in rows if line.strip()]


def plan_for(table, dumped, live):
    """What a restore would do to one table, in the four things it can do.

    Rows are matched by their key rather than by their contents, so a row that
    exists in both but differs is reported as replaced - which is the fact a
    person wants before writing over an account: not "these rows are here" but
    "these six are fine and this one would change".
    """
    live_by_key = {key_of(table, row): row for row in live}
    dumped_by_key = {key_of(table, row): row for row in dumped}
    inserted, replaced, identical = [], [], []
    for key, row in dumped_by_key.items():
        other = live_by_key.get(key)
        if other is None:
            inserted.append(key)
        elif backup.canonical_row(other) == backup.canonical_row(row):
            identical.append(key)
        else:
            replaced.append(key)
    removed = [key for key in live_by_key if key not in dumped_by_key]
    return {"inserted": sorted(inserted), "replaced": sorted(replaced),
            "identical": sorted(identical), "removed": sorted(removed)}


def restore_sql(table, columns, rows, user_ids, dry_run):
    """The statements that put one table's rows back for those accounts.

    Delete first, then insert: the account's rows in this table become the rows in
    the file and nothing else. The delete is scoped to the accounts named, so a
    restore can only reach what it was asked about, and the insert carries the
    dumped columns by name rather than trusting the table's column order.
    """
    if not user_ids:
        return []
    lines = []
    array = "array[" + ", ".join(backup.sql_text(u) for u in sorted(user_ids)) + "]::uuid[]"
    lines.append("delete from public." + backup.quote_ident(table)
                 + " where " + backup.quote_ident(USER_COLUMN) + " = any (" + array + ");")
    # The column list comes before OVERRIDING SYSTEM VALUE, which is the order
    # Postgres' own grammar asks for - and the clause is what lets the dumped
    # decks.id through a column that is "generated always as identity".
    names = ", ".join(backup.quote_ident(column) for column in columns)
    target = ("insert into public." + backup.quote_ident(table) + " (" + names + ")"
              + (" overriding system value" if table in GENERATED_KEYS else ""))
    for start in range(0, len(rows), BATCH):
        batch = rows[start:start + BATCH]
        values = ", ".join(
            "(" + backup.sql_text(json.dumps(row, ensure_ascii=False,
                                             sort_keys=True,
                                             separators=(",", ":"))) + "::jsonb)"
            for row in batch)
        lines.append(
            target + chr(10)
            + "select r.* from (values " + values + ") as v(row_object),"
            + " jsonb_populate_record(null::public." + backup.quote_ident(table)
            + ", v.row_object) r;")
    return lines


def counts_now(db_url, tables, user_ids, timeout=backup.TIMEOUT):
    """How many rows those accounts hold in each table, read in one statement."""
    if not user_ids:
        return {}
    array = "array[" + ", ".join(backup.sql_text(u) for u in sorted(user_ids)) + "]::uuid[]"
    statements = [
        "select " + backup.sql_text("count=" + table + "=")
        + " || count(*)::text from public." + backup.quote_ident(table)
        + " where " + backup.quote_ident(USER_COLUMN) + " = any (" + array + ");"
        for table in tables
    ]
    sql = ("begin isolation level repeatable read read only;" + chr(10)
           + chr(10).join(statements) + chr(10) + "commit;")
    counts = {}
    for line in backup.psql_lines(db_url, sql, timeout):
        label, _, number = line.partition("=")
        if label != "count" or "=" not in number:
            continue
        table, _, value = number.partition("=")
        counts[table] = int(value)
    return counts


def describe(table, result, limit=3):
    """One line saying what would change in one table."""
    parts = []
    for what in ("inserted", "replaced", "removed", "identical"):
        parts.append("%d %s" % (len(result[what]), what))
    line = "  %-20s %s" % (table, ", ".join(parts))
    interesting = (result["replaced"] + result["inserted"] + result["removed"])
    if interesting:
        shown = ["/".join(key) for key in interesting[:limit]]
        line += "  (" + ", ".join(shown)
        if len(interesting) > limit:
            line += ", and %d more" % (len(interesting) - limit)
        line += ")"
    return line


def run(args, db_url):
    directory = args.out_dir or backup.DEFAULT_DIR
    path = resolve_dump(args.from_dump, directory)
    if path is None:
        return 2
    try:
        header, rows = backup.read_dump(path)
    except backup.DumpError as exc:
        print("the dump could not be read: %s" % exc, file=sys.stderr, flush=True)
        return 2

    held = [table for table in backup.TABLES if table in rows]
    missing = [table for table in backup.TABLES if table not in rows]
    print("%s, taken %s, version %s, holds %d table(s): %s"
          % (os.path.basename(path), header.get("created_at"), header.get("version"),
             len(held),
             ", ".join("%s %d" % (table, header["rows"].get(table, 0))
                       for table in held)))
    if missing:
        print("  this dump holds no %s, so a restore from it cannot put those rows "
              "back: a version-%s dump predates them" % (", ".join(missing),
                                                          header.get("version")),
              flush=True)

    users = resolve_users(db_url, args)
    if users is None:
        return 2
    named, unknown = users
    for email in known_order(args, named):
        print("  %s is %s in auth.users" % (email, named[email]), flush=True)
    if unknown:
        print("no account is registered as %s, so there is nothing to restore to: "
              "the account tables point at auth.users and a restore cannot invent a "
              "collector" % ", ".join(unknown), file=sys.stderr, flush=True)
        return 2

    user_ids = list(named.values())
    tables = held
    before = counts_now(db_url, tables, user_ids)
    statements = ["begin;", "set local time zone 'UTC';"]
    total = {}

    print("", flush=True)
    for table in tables:
        columns = table_columns_of(header, table)
        dumped = [row for row in rows[table]
                  if str(row.get(USER_COLUMN)) in set(user_ids)]
        live = live_rows(db_url, table, columns, user_ids)
        result = plan_for(table, dumped, live)
        total[table] = result
        print(describe(table, result), flush=True)
        statements.extend(restore_sql(table, columns, dumped, user_ids, args.dry_run))

    if args.dry_run:
        statements.append("rollback;")
    else:
        statements.append("commit;")

    try:
        backup.psql_lines(db_url, chr(10).join(statements))
    except backup.DumpError as exc:
        print("the restore did not complete: %s" % exc, file=sys.stderr, flush=True)
        print("nothing was written: every statement above was inside one "
              "transaction, and a failure rolls the whole thing back", flush=True)
        return 1

    after = counts_now(db_url, tables, user_ids)
    print("", flush=True)
    if args.dry_run:
        if before != after:
            print("the dry run changed the tables, which it must not: %s became %s"
                  % (before, after), file=sys.stderr, flush=True)
            return 1
        print("dry run: the statements ran inside a transaction that was rolled "
              "back, and the account still holds %s"
              % ", ".join("%d %s" % (count, table) for table, count in sorted(after.items())),
              flush=True)
        print("nothing was written. Run it again with --apply to mean it.", flush=True)
        return 0

    print("written: the account now holds %s"
          % ", ".join("%d %s" % (count, table) for table, count in sorted(after.items())),
          flush=True)
    for table in tables:
        result = total[table]
        print("  %-20s %d inserted, %d replaced, %d removed"
              % (table, len(result["inserted"]), len(result["replaced"]),
                 len(result["removed"])), flush=True)
    return 0


def known_order(args, named):
    """The emails in the order the arguments named them, for a stable log."""
    order = []
    for email in (args.user or []):
        low = email.strip().lower()
        for known in named:
            if known.lower() == low:
                order.append(known)
    if not order:
        order = sorted(named)
    return order


def resolve_users(db_url, args):
    """The accounts to restore, as (email -> uuid, unknown emails)."""
    if args.every_account:
        rows = backup.psql_lines(
            db_url, "select id::text || ' ' || email from auth.users order by email;")
        named = {}
        for line in rows:
            parts = line.strip().split(" ", 1)
            if len(parts) == 2 and parts[0]:
                named[parts[1].strip()] = parts[0]
        return (named, []) if named else None
    named, unknown = {}, []
    for email in (args.user or []):
        found = user_id_of(db_url, email.strip())
        if found is None:
            unknown.append(email.strip())
        else:
            named[email.strip()] = found
    return named, unknown


def resolve_dump(name, directory):
    """The dump to restore from: newest, a name in the directory, or a path."""
    if not name or name == "newest":
        dumps = backup.dump_files(directory)
        if not dumps:
            print("no dump in %s: there is nothing to restore from" % directory,
                  file=sys.stderr, flush=True)
            return None
        return dumps[-1]
    if os.path.isabs(name) or os.path.exists(name):
        return name
    candidate = os.path.join(directory, name)
    if os.path.exists(candidate):
        return candidate
    if not name.endswith(backup.BACKUP_SUFFIX):
        candidate = os.path.join(directory, name + backup.BACKUP_SUFFIX)
        if os.path.exists(candidate):
            return candidate
    print("%s is neither a file nor a dump in %s" % (name, directory),
          file=sys.stderr, flush=True)
    return None


def parse_args(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="from_dump", default="newest",
                    help="a dump file, a name in --out-dir, or 'newest' (the default)")
    ap.add_argument("--out-dir", default=backup.DEFAULT_DIR,
                    help="where the dumps are (default %s)" % backup.DEFAULT_DIR)
    ap.add_argument("--user", action="append", default=[],
                    help="an account's email address; repeat for more than one")
    ap.add_argument("--every-account", action="store_true",
                    help="every account in the project - the project-is-gone case")
    ap.add_argument("--apply", action="store_true",
                    help="write it; without this the restore is planned and rolled back")
    ap.add_argument("--dry-run", action="store_true",
                    help="the default, said out loud; --apply turns it off")
    ap.add_argument("--env-file", default=backup.DEFAULT_ENV_FILE,
                    help="a KEY=VALUE file to read the credentials from")
    return ap.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    if args.apply:
        args.dry_run = False
    else:
        args.dry_run = True
    if not args.user and not args.every_account:
        print("this restores rows over what somebody has, so it needs to know "
              "whose: --user someone@example.com, or --every-account when the "
              "project itself is gone", file=sys.stderr)
        return 2

    if args.env_file:
        if os.path.exists(args.env_file):
            backup.load_env_file(args.env_file)
        elif args.env_file != backup.DEFAULT_ENV_FILE:
            print("%s does not exist" % args.env_file, file=sys.stderr)
            return 2

    try:
        db_url = backup.database_url()
        backup.require_libpq_split()
        backup.catalog_store.find_psql()
    except (backup.DumpError, backup.catalog_store.CatalogError) as exc:
        print(str(exc), file=sys.stderr)
        return 2

    # The backup's own lock, taken the way the backup takes it. Not because a
    # dump and a restore can tear each other - the dump reads one repeatable-read
    # snapshot - but because of the assertion this file makes about itself: a dry
    # run that says the account still holds what it held is only saying something
    # if nothing else was writing to those tables while it looked.
    try:
        with backup.catalog_store.single_flight(backup.DEFAULT_LOCK):
            return run(args, db_url)
    except (backup.DumpError, backup.catalog_store.CatalogError) as exc:
        print("the restore refused to start: %s" % exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
