import 'dart:math' as math;

import 'package:flutter/foundation.dart' show listEquals;
import 'package:flutter/material.dart';

import '../core/theme/app_theme.dart';

/// A dependency-free trend line with a smooth (Catmull-Rom) curve, a soft
/// gradient area fill and a subtle glow underneath the stroke.
///
/// Degrades gracefully: fewer than two values, a constant series or a series
/// containing `NaN`/`Infinity` all render a clean flat line rather than
/// throwing.
class Sparkline extends StatelessWidget {
  /// Creates a sparkline for [values].
  const Sparkline({
    super.key,
    required this.values,
    this.color,
    this.height = 40,
    this.strokeWidth = 1.8,
    this.fill = true,
    this.baseline,
    this.semanticLabel,
  });

  /// The series to plot, oldest first. Non-finite entries are ignored.
  final List<double> values;

  /// Stroke colour. Defaults to [ArcanumColors.accent].
  final Color? color;

  /// Height of the plot. The widget expands to fill the available width.
  final double height;

  /// Stroke width in logical pixels.
  final double strokeWidth;

  /// Whether to paint the gradient area fill beneath the line.
  final bool fill;

  /// Optional horizontal reference line, usually a cost basis or a zero line.
  final double? baseline;

  /// Optional semantics label. A sensible one is generated by default.
  final String? semanticLabel;

  @override
  Widget build(BuildContext context) {
    final c = context.c;
    return Semantics(
      label: semanticLabel ?? _describe(),
      excludeSemantics: true,
      child: SizedBox(
        height: height,
        width: double.infinity,
        child: CustomPaint(
          painter: SparklinePainter(
            values: values,
            color: color ?? c.accent,
            strokeWidth: strokeWidth,
            fill: fill,
            baseline: baseline,
          ),
        ),
      ),
    );
  }

  String _describe() {
    final finite = values.where((double v) => v.isFinite).toList();
    if (finite.isEmpty) return 'Trend line with no data';
    if (finite.length == 1) return 'Trend line, single value';
    final first = finite.first;
    final last = finite.last;
    final direction = last > first
        ? 'rising'
        : (last < first ? 'falling' : 'flat');
    return 'Trend line, ${finite.length} points, $direction';
  }
}

/// Paints a [Sparkline]. Public so it can be unit-tested directly.
class SparklinePainter extends CustomPainter {
  /// Creates a painter for [values].
  SparklinePainter({
    required this.values,
    required this.color,
    this.strokeWidth = 1.8,
    this.fill = true,
    this.baseline,
  });

  /// The series to plot, oldest first.
  final List<double> values;

  /// Stroke and fill colour.
  final Color color;

  /// Stroke width in logical pixels.
  final double strokeWidth;

  /// Whether to paint the gradient area fill.
  final bool fill;

  /// Optional horizontal reference line.
  final double? baseline;

  /// Blur radius of the glow painted under the stroke.
  static const double glowSigma = 3;

  @override
  void paint(Canvas canvas, Size size) {
    if (size.width <= 0 || size.height <= 0) return;

    final data = _sanitized();
    final pad = strokeWidth / 2 + 1;
    final usable = math.max(1.0, size.height - pad * 2);
    final midY = size.height / 2;

    final path = Path();
    var flat = true;
    double? baselineY;

    if (data.length < 2) {
      path.moveTo(0, midY);
      path.lineTo(size.width, midY);
    } else {
      final minV = data.reduce(math.min);
      final maxV = data.reduce(math.max);
      final span = maxV - minV;
      flat = span.abs() < 1e-9;

      double mapY(double v) => pad + (1 - (v - minV) / span) * usable;

      if (flat) {
        path.moveTo(0, midY);
        path.lineTo(size.width, midY);
      } else {
        final pts = <Offset>[
          for (var i = 0; i < data.length; i++)
            Offset(size.width * (i / (data.length - 1)), mapY(data[i])),
        ];
        path.moveTo(pts.first.dx, pts.first.dy);
        for (var i = 0; i < pts.length - 1; i++) {
          final p0 = pts[i == 0 ? 0 : i - 1];
          final p1 = pts[i];
          final p2 = pts[i + 1];
          final p3 = pts[i + 2 >= pts.length ? pts.length - 1 : i + 2];
          path.cubicTo(
            p1.dx + (p2.dx - p0.dx) / 6,
            p1.dy + (p2.dy - p0.dy) / 6,
            p2.dx - (p3.dx - p1.dx) / 6,
            p2.dy - (p3.dy - p1.dy) / 6,
            p2.dx,
            p2.dy,
          );
        }
      }

      final b = baseline;
      if (b != null && b.isFinite && !flat) {
        baselineY = mapY(b).clamp(pad, size.height - pad).toDouble();
      }
    }

    if (fill && !flat) {
      final area = Path.from(path)
        ..lineTo(size.width, size.height)
        ..lineTo(0, size.height)
        ..close();
      canvas.drawPath(
        area,
        Paint()
          ..shader = LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: <Color>[
              color.withValues(alpha: 0.30),
              color.withValues(alpha: 0),
            ],
          ).createShader(Offset.zero & size),
      );
    }

    if (baselineY != null) {
      canvas.drawLine(
        Offset(0, baselineY),
        Offset(size.width, baselineY),
        Paint()
          ..color = color.withValues(alpha: 0.28)
          ..strokeWidth = 1,
      );
    }

    canvas.drawPath(
      path,
      Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = strokeWidth * 2.6
        ..strokeCap = StrokeCap.round
        ..strokeJoin = StrokeJoin.round
        ..color = color.withValues(alpha: 0.20)
        ..maskFilter = const MaskFilter.blur(BlurStyle.normal, glowSigma),
    );

    canvas.drawPath(
      path,
      Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = strokeWidth
        ..strokeCap = StrokeCap.round
        ..strokeJoin = StrokeJoin.round
        ..isAntiAlias = true
        ..color = color,
    );
  }

  /// Replaces non-finite samples with the last known good value.
  List<double> _sanitized() {
    if (values.isEmpty) return const <double>[];
    final out = <double>[];
    var last = 0.0;
    for (final v in values) {
      final safe = v.isFinite ? v : last;
      out.add(safe);
      last = safe;
    }
    return out;
  }

  @override
  bool shouldRepaint(SparklinePainter oldDelegate) =>
      !listEquals(oldDelegate.values, values) ||
      oldDelegate.color != color ||
      oldDelegate.strokeWidth != strokeWidth ||
      oldDelegate.fill != fill ||
      oldDelegate.baseline != baseline;
}
